# Generated by Django 5.2.3 on 2025-06-22 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_order_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID платежа'),
        ),
        migrations.AddField(
            model_name='product',
            name='reserved',
            field=models.PositiveIntegerField(default=0, verbose_name='Зарезервировано'),
        ),
    ]
