# Generated by Django 5.2.3 on 2025-06-19 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(unique=True, verbose_name='Telegram Chat ID')),
                ('username', models.CharField(blank=True, max_length=32, verbose_name='Telegram Username')),
                ('first_name', models.CharField(blank=True, max_length=64, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=64, verbose_name='Фамилия')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
    ]
